In [1]:
# Importation des modules
import pandas as pd
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt
import re

# Modifier les options d'affichage pour limiter les décimales
pd.set_option('display.float_format', lambda x: '%.2f' % x)

In [2]:
# Affichage de la BDD
TmdbCleanDumActor_Final = pd.read_csv('BDD_CSV/last_BDD/TmdbCleanDumActor_Final.csv')
print(TmdbCleanDumActor_Final.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 251523 entries, 0 to 251522
Data columns (total 43 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   ID_title                251523 non-null  object
 1   title                   251523 non-null  object
 2   original_title          251523 non-null  object
 3   ID_name                 251523 non-null  object
 4   actor_name              251523 non-null  object
 5   actor                   251523 non-null  float64
 6   actress                 251523 non-null  float64
 7   director                251523 non-null  float64
 8   original_language       27345 non-null   object
 9   release_year            251523 non-null  int64
 10  runtime_minutes         251523 non-null  int64
 11  weighted_averageRating  251523 non-null  float64
 12  average_rating          251523 non-null  float64
 13  numVotes                251523 non-null  float64
 14  popularity              27345 non-null   float64
 15  genres                  251523 non-null  object
 16  Action                  251523 non-null  int64
 17  Adventure               251523 non-null  int64
 18  Biography               251523 non-null  int64
 19  Crime                   251523 non-null  int64
 20  Documentary             251523 non-null  int64
 21  Fantasy                 251523 non-null  int64
 22  Game-Show               251523 non-null  int64
 23  Horror                  251523 non-null  int64
 24  Musical                 251523 non-null  int64
 25  Mystery                 251523 non-null  int64
 26  News                    251523 non-null  int64
 27  Reality-TV              251523 non-null  int64
 28  Sport                   251523 non-null  int64
 29  Talk-Show               251523 non-null  int64
 30  Thriller                251523 non-null  int64
 31  War                     251523 non-null  int64
 32  Western                 251523 non-null  int64
 33  Animation               251523 non-null  int64
 34  Comedy                  251523 non-null  int64
 35  Drama                   251523 non-null  int64
 36  Family                  251523 non-null  int64
 37  History                 251523 non-null  int64
 38  Music                   251523 non-null  int64
 39  Romance                 251523 non-null  int64
 40  ScienceFiction          251523 non-null  int64
 41  overview                27345 non-null   object
 42  poster_path             27013 non-null   object
dtypes: float64(7), int64(27), object(9)
memory usage: 82.5+ MB
None

In [3]:
# Affichage
print(TmdbCleanDumActor_Final.sample(1).to_markdown(index=False, numalign="left", stralign="left"))

| ID_title   | title    | original_title   | ID_name   | actor_name    | actor   | actress   | director   | original_language   | release_year   | runtime_minutes   | weighted_averageRating   | average_rating   | numVotes   | popularity   | genres      | Action   | Adventure   | Biography   | Crime   | Documentary   | Fantasy   | Game-Show   | Horror   | Musical   | Mystery   | News   | Reality-TV   | Sport   | Talk-Show   | Thriller   | War   | Western   | Animation   | Comedy   | Drama   | Family   | History   | Music   | Romance   | ScienceFiction   | overview   | poster_path   |
|:-----------|:---------|:-----------------|:----------|:--------------|:--------|:----------|:-----------|:--------------------|:---------------|:------------------|:-------------------------|:-----------------|:-----------|:-------------|:------------|:---------|:------------|:------------|:--------|:--------------|:----------|:------------|:---------|:----------|:----------|:-------|:-------------|:--------|:------------|:-----------|:------|:----------|:------------|:---------|:--------|:---------|:----------|:--------|:----------|:-----------------|:-----------|:--------------|
| tt0128442  | Rounders | Rounders         | nm0001570 | Edward Norton | 1       | 0         | 0          | nan                 | 1998           | 121               | 7.29776                  | 7.3              | 160726     | nan          | Crime,Drama | 0        | 0           | 0           | 1       | 0             | 0         | 0           | 0        | 0         | 0         | 0      | 0            | 0       | 0           | 0          | 0     | 0         | 0           | 0        | 1       | 0        | 0         | 0       | 0         | 0                | nan        | nan           |

In [4]:
# Initialisation des comptes de NaN
nan_counts_per_column = {}
total_nan_counts = 0

# Boucle sur chaque colonne et comptage des NaN
for column in TmdbCleanDumActor_Final.columns:
    nan_count = TmdbCleanDumActor_Final[column].isna().sum()
    nan_counts_per_column[column] = nan_count
    total_nan_counts += nan_count

# Affichage des résultats
print("Nombre de NaN par colonne:")
for column, count in nan_counts_per_column.items():
    print(f"Colonne {column}: {count} NaN")

Nombre de NaN par colonne:
Colonne ID_title: 0 NaN
Colonne title: 0 NaN
Colonne original_title: 0 NaN
Colonne ID_name: 0 NaN
Colonne actor_name: 0 NaN
Colonne actor: 0 NaN
Colonne actress: 0 NaN
Colonne director: 0 NaN
Colonne original_language: 224178 NaN
Colonne release_year: 0 NaN
Colonne runtime_minutes: 0 NaN
Colonne weighted_averageRating: 0 NaN
Colonne average_rating: 0 NaN
Colonne numVotes: 0 NaN
Colonne popularity: 224178 NaN
Colonne genres: 0 NaN
Colonne Action: 0 NaN
Colonne Adventure: 0 NaN
Colonne Biography: 0 NaN
Colonne Crime: 0 NaN
Colonne Documentary: 0 NaN
Colonne Fantasy: 0 NaN
Colonne Game-Show: 0 NaN
Colonne Horror: 0 NaN
Colonne Musical: 0 NaN
Colonne Mystery: 0 NaN
Colonne News: 0 NaN
Colonne Reality-TV: 0 NaN
Colonne Sport: 0 NaN
Colonne Talk-Show: 0 NaN
Colonne Thriller: 0 NaN
Colonne War: 0 NaN
Colonne Western: 0 NaN
Colonne Animation: 0 NaN
Colonne Comedy: 0 NaN
Colonne Drama: 0 NaN
Colonne Family: 0 NaN
Colonne History: 0 NaN
Colonne Music: 0 NaN
Colonne Romance: 0 NaN
Colonne ScienceFiction: 0 NaN
Colonne overview: 224178 NaN
Colonne poster_path: 224510 NaN

In [5]:
# Affichage de la BDD
df_netflix = pd.read_csv('BDD_CSV/last_BDD/netflix.csv')
print(df_netflix.info())
print(df_netflix.sample(2).to_markdown(index=False, numalign="left", stralign="left"))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31138 entries, 0 to 31137
Data columns (total 43 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ID_title                31138 non-null  object
 1   title                   31138 non-null  object
 2   original_title          31138 non-null  object
 3   ID_name                 31138 non-null  object
 4   actor_name              31138 non-null  object
 5   actor                   31138 non-null  float64
 6   actress                 31138 non-null  float64
 7   director                31138 non-null  float64
 8   original_language       31138 non-null  object
 9   release_year            31138 non-null  int64
 10  runtime_minutes         31138 non-null  int64
 11  weighted_averageRating  31138 non-null  float64
 12  average_rating          31138 non-null  float64
 13  numVotes                31138 non-null  float64
 14  popularity              26938 non-null  float64
 15  genres                  31138 non-null  object
 16  Action                  31138 non-null  int64
 17  Adventure               31138 non-null  int64
 18  Biography               31138 non-null  int64
 19  Crime                   31138 non-null  int64
 20  Documentary             31138 non-null  int64
 21  Fantasy                 31138 non-null  int64
 22  Game-Show               31138 non-null  int64
 23  Horror                  31138 non-null  int64
 24  Musical                 31138 non-null  int64
 25  Mystery                 31138 non-null  int64
 26  News                    31138 non-null  int64
 27  Reality-TV              31138 non-null  int64
 28  Sport                   31138 non-null  int64
 29  Talk-Show               31138 non-null  int64
 30  Thriller                31138 non-null  int64
 31  War                     31138 non-null  int64
 32  Western                 31138 non-null  int64
 33  Animation               31138 non-null  int64
 34  Comedy                  31138 non-null  int64
 35  Drama                   31138 non-null  int64
 36  Family                  31138 non-null  int64
 37  History                 31138 non-null  int64
 38  Music                   31138 non-null  int64
 39  Romance                 31138 non-null  int64
 40  ScienceFiction          31138 non-null  int64
 41  overview                26938 non-null  object
 42  poster_path             26606 non-null  object
dtypes: float64(7), int64(27), object(9)
memory usage: 10.2+ MB
None
| ID_title   | title       | original_title   | ID_name   | actor_name       | actor   | actress   | director   | original_language   | release_year   | runtime_minutes   | weighted_averageRating   | average_rating   | numVotes   | popularity   | genres                 | Action   | Adventure   | Biography   | Crime   | Documentary   | Fantasy   | Game-Show   | Horror   | Musical   | Mystery   | News   | Reality-TV   | Sport   | Talk-Show   | Thriller   | War   | Western   | Animation   | Comedy   | Drama   | Family   | History   | Music   | Romance   | ScienceFiction   | overview                                                                                                                                                                                                                                                                                                                                         | poster_path                      |
|:-----------|:------------|:-----------------|:----------|:-----------------|:--------|:----------|:-----------|:--------------------|:---------------|:------------------|:-------------------------|:-----------------|:-----------|:-------------|:-----------------------|:---------|:------------|:------------|:--------|:--------------|:----------|:------------|:---------|:----------|:----------|:-------|:-------------|:--------|:------------|:-----------|:------|:----------|:------------|:---------|:--------|:---------|:----------|:--------|:----------|:-----------------|:-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:---------------------------------|
| tt1596346  | Soul Surfer | Soul Surfer      | nm0000598 | Dennis Quaid     | 1       | 0         | 0          | en                  | 2011           | 112               | 6.99515                  | 7                | 53083      | 23.995       | Biography,Drama,Family | 0        | 0           | 1           | 0       | 0             | 0         | 0           | 0        | 0         | 0         | 0      | 0            | 0       | 0           | 0          | 0     | 0         | 0           | 0        | 1       | 1        | 0         | 0       | 0         | 0                | The true story of teen surfer Bethany Hamilton, who lost her arm in a shark attack and courageously overcame all odds to become a champion again, through her sheer determination and unwavering faith.                                                                                                                                          | /urLCQDCOITabAud39ZwLbNFBrc4.jpg |
| tt0472462  | Gol & Gincu | Gol & Gincu      | nm1984716 | Rafidah Abdullah | 0       | 1         | 1          | ms                  | 2005           | 104               | 6.28317                  | 6.4              | 126        | 0.844        | Comedy,Romance,Sport   | 0        | 0           | 0           | 0       | 0             | 0         | 0           | 0        | 0         | 0         | 0      | 0            | 1       | 0           | 0          | 0     | 0         | 0           | 1        | 0       | 0        | 0         | 0       | 1         | 0                | Putri is determined to win back her sports-mad ex-boyfriend, Eddy by turning into a futsal heroine herself. Facing prejudice and ridicule, and discovering, through her motley futsal team, the many difficulties faced by women in sports, Putri gradually finds within herself the strength and values of a true winner, on and off the pitch. | /kaEy0EfI8gTE8RsXFTDG1O6N4oI.jpg |

#### ***Merge de TmdbCleanDumActor_Final et netflix***

In [6]:
df_final = TmdbCleanDumActor_Final.merge(right= df_netflix, on="ID_title", how='left')

In [7]:
print(df_final.info())
print(df_final.sample(2).to_markdown(index=False, numalign="left", stralign="left"))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 521265 entries, 0 to 521264
Data columns (total 85 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   ID_title                  521265 non-null  object
 1   title_x                   521265 non-null  object
 2   original_title_x          521265 non-null  object
 3   ID_name_x                 521265 non-null  object
 4   actor_name_x              521265 non-null  object
 5   actor_x                   521265 non-null  float64
 6   actress_x                 521265 non-null  float64
 7   director_x                521265 non-null  float64
 8   original_language_x       260283 non-null  object
 9   release_year_x            521265 non-null  int64
 10  runtime_minutes_x         521265 non-null  int64
 11  weighted_averageRating_x  521265 non-null  float64
 12  average_rating_x          521265 non-null  float64
 13  numVotes_x                521265 non-null  float64
 14  popularity_x              260283 non-null  float64
 15  genres_x                  521265 non-null  object
 16  Action_x                  521265 non-null  int64
 17  Adventure_x               521265 non-null  int64
 18  Biography_x               521265 non-null  int64
 19  Crime_x                   521265 non-null  int64
 20  Documentary_x             521265 non-null  int64
 21  Fantasy_x                 521265 non-null  int64
 22  Game-Show_x               521265 non-null  int64
 23  Horror_x                  521265 non-null  int64
 24  Musical_x                 521265 non-null  int64
 25  Mystery_x                 521265 non-null  int64
 26  News_x                    521265 non-null  int64
 27  Reality-TV_x              521265 non-null  int64
 28  Sport_x                   521265 non-null  int64
 29  Talk-Show_x               521265 non-null  int64
 30  Thriller_x                521265 non-null  int64
 31  War_x                     521265 non-null  int64
 32  Western_x                 521265 non-null  int64
 33  Animation_x               521265 non-null  int64
 34  Comedy_x                  521265 non-null  int64
 35  Drama_x                   521265 non-null  int64
 36  Family_x                  521265 non-null  int64
 37  History_x                 521265 non-null  int64
 38  Music_x                   521265 non-null  int64
 39  Romance_x                 521265 non-null  int64
 40  ScienceFiction_x          521265 non-null  int64
 41  overview_x                260283 non-null  object
 42  poster_path_x             257511 non-null  object
 43  title_y                   300880 non-null  object
 44  original_title_y          300880 non-null  object
 45  ID_name_y                 300880 non-null  object
 46  actor_name_y              300880 non-null  object
 47  actor_y                   300880 non-null  float64
 48  actress_y                 300880 non-null  float64
 49  director_y                300880 non-null  float64
 50  original_language_y       300880 non-null  object
 51  release_year_y            300880 non-null  float64
 52  runtime_minutes_y         300880 non-null  float64
 53  weighted_averageRating_y  300880 non-null  float64
 54  average_rating_y          300880 non-null  float64
 55  numVotes_y                300880 non-null  float64
 56  popularity_y              259876 non-null  float64
 57  genres_y                  300880 non-null  object
 58  Action_y                  300880 non-null  float64
 59  Adventure_y               300880 non-null  float64
 60  Biography_y               300880 non-null  float64
 61  Crime_y                   300880 non-null  float64
 62  Documentary_y             300880 non-null  float64
 63  Fantasy_y                 300880 non-null  float64
 64  Game-Show_y               300880 non-null  float64
 65  Horror_y                  300880 non-null  float64
 66  Musical_y                 300880 non-null  float64
 67  Mystery_y                 300880 non-null  float64
 68  News_y                    300880 non-null  float64
 69  Reality-TV_y              300880 non-null  float64
 70  Sport_y                   300880 non-null  float64
 71  Talk-Show_y               300880 non-null  float64
 72  Thriller_y                300880 non-null  float64
 73  War_y                     300880 non-null  float64
 74  Western_y                 300880 non-null  float64
 75  Animation_y               300880 non-null  float64
 76  Comedy_y                  300880 non-null  float64
 77  Drama_y                   300880 non-null  float64
 78  Family_y                  300880 non-null  float64
 79  History_y                 300880 non-null  float64
 80  Music_y                   300880 non-null  float64
 81  Romance_y                 300880 non-null  float64
 82  ScienceFiction_y          300880 non-null  float64
 83  overview_y                259876 non-null  object
 84  poster_path_y             257104 non-null  object
dtypes: float64(41), int64(27), object(17)
memory usage: 338.0+ MB
None
| ID_title   | title_x           | original_title_x    | ID_name_x   | actor_name_x   | actor_x   | actress_x   | director_x   | original_language_x   | release_year_x   | runtime_minutes_x   | weighted_averageRating_x   | average_rating_x   | numVotes_x   | popularity_x   | genres_x   | Action_x   | Adventure_x   | Biography_x   | Crime_x   | Documentary_x   | Fantasy_x   | Game-Show_x   | Horror_x   | Musical_x   | Mystery_x   | News_x   | Reality-TV_x   | Sport_x   | Talk-Show_x   | Thriller_x   | War_x   | Western_x   | Animation_x   | Comedy_x   | Drama_x   | Family_x   | History_x   | Music_x   | Romance_x   | ScienceFiction_x   | overview_x                                                                                                                                                                                                                                                                                                                                                                            | poster_path_x                    | title_y           | original_title_y    | ID_name_y   | actor_name_y       | actor_y   | actress_y   | director_y   | original_language_y   | release_year_y   | runtime_minutes_y   | weighted_averageRating_y   | average_rating_y   | numVotes_y   | popularity_y   | genres_y   | Action_y   | Adventure_y   | Biography_y   | Crime_y   | Documentary_y   | Fantasy_y   | Game-Show_y   | Horror_y   | Musical_y   | Mystery_y   | News_y   | Reality-TV_y   | Sport_y   | Talk-Show_y   | Thriller_y   | War_y   | Western_y   | Animation_y   | Comedy_y   | Drama_y   | Family_y   | History_y   | Music_y   | Romance_y   | ScienceFiction_y   | overview_y                                                                                                                                                                                                                                                                                                                                                                            | poster_path_y                    |
|:-----------|:------------------|:--------------------|:------------|:---------------|:----------|:------------|:-------------|:----------------------|:-----------------|:--------------------|:---------------------------|:-------------------|:-------------|:---------------|:-----------|:-----------|:--------------|:--------------|:----------|:----------------|:------------|:--------------|:-----------|:------------|:------------|:---------|:---------------|:----------|:--------------|:-------------|:--------|:------------|:--------------|:-----------|:----------|:-----------|:------------|:----------|:------------|:-------------------|:--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:---------------------------------|:------------------|:--------------------|:------------|:-------------------|:----------|:------------|:-------------|:----------------------|:-----------------|:--------------------|:---------------------------|:-------------------|:-------------|:---------------|:-----------|:-----------|:--------------|:--------------|:----------|:----------------|:------------|:--------------|:-----------|:------------|:------------|:---------|:---------------|:----------|:--------------|:-------------|:--------|:------------|:--------------|:-----------|:----------|:-----------|:------------|:----------|:------------|:-------------------|:--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:---------------------------------|
| tt0218839  | Best in Show      | Best in Show        | nm0929609   | Fred Willard   | 1         | 0           | 0            | en                    | 2000             | 90                  | 7.49364                    | 7.5                | 67241        | 13.21          | Comedy     | 0          | 0             | 0             | 0         | 0               | 0           | 0             | 0          | 0           | 0           | 0        | 0              | 0         | 0             | 0            | 0       | 0           | 0             | 1          | 0         | 0          | 0           | 0         | 0           | 0                  | The tension is palpable, the excitement is mounting and the heady scent of competition is in the air as hundreds of eager contestants from across America prepare to take part in what is undoubtedly one of the greatest events of their lives -- the Mayflower Dog Show. The canine contestants and their owners are as wondrously diverse as the great country that has bred them. | /kVNaXzoX64YwLC99o4gXyKPnplS.jpg | Best in Show      | Best in Show        | nm0106319   | Jay Brazeau        | 1         | 0           | 0            | en                    | 2000             | 90                  | 7.49364                    | 7.5                | 67241        | 13.21          | Comedy     | 0          | 0             | 0             | 0         | 0               | 0           | 0             | 0          | 0           | 0           | 0        | 0              | 0         | 0             | 0            | 0       | 0           | 0             | 1          | 0         | 0          | 0           | 0         | 0           | 0                  | The tension is palpable, the excitement is mounting and the heady scent of competition is in the air as hundreds of eager contestants from across America prepare to take part in what is undoubtedly one of the greatest events of their lives -- the Mayflower Dog Show. The canine contestants and their owners are as wondrously diverse as the great country that has bred them. | /kVNaXzoX64YwLC99o4gXyKPnplS.jpg |
| tt8343886  | The August Virgin | La virgen de agosto | nm3943753   | Joe Manjón     | 1         | 0           | 0            | es                    | 2019             | 125                 | 6.53606                    | 6.6                | 1579         | 4.931          | Drama      | 0          | 0             | 0             | 0         | 0               | 0           | 0             | 0          | 0           | 0           | 0        | 0              | 0         | 0             | 0            | 0       | 0           | 0             | 0          | 1         | 0          | 0           | 0         | 0           | 0                  | Young Eva makes her decision to stay in Madrid for the month of August an act of faith. She needs to feel things differently and think of summer as a time of opportunity. On days of festivities and verbenas, while events and encounters take place, Eva will discover that she still has time, that an opportunity can still be given.                                            | /ybsLltBY2HWE43mvDgfW8nnDldh.jpg | The August Virgin | La virgen de agosto | nm4414800   | Luis Alberto Heras | 1         | 0           | 0            | es                    | 2019             | 125                 | 6.53606                    | 6.6                | 1579         | 4.931          | Drama      | 0          | 0             | 0             | 0         | 0               | 0           | 0             | 0          | 0           | 0           | 0        | 0              | 0         | 0             | 0            | 0       | 0           | 0             | 0          | 1         | 0          | 0           | 0         | 0           | 0                  | Young Eva makes her decision to stay in Madrid for the month of August an act of faith. She needs to feel things differently and think of summer as a time of opportunity. On days of festivities and verbenas, while events and encounters take place, Eva will discover that she still has time, that an opportunity can still be given.                                            | /ybsLltBY2HWE43mvDgfW8nnDldh.jpg |

In [8]:
# Remplacer les NaN dans 'original_language_x' par les valeurs correspondantes de 'original_language_y' provenant de netflix
df_final['original_language_x'] = df_final['original_language_x'].fillna(df_final['original_language_y'])

In [9]:
# Suppression des colonnes avec le suffixe `_y`
df_final = df_final.loc[:, ~df_final.columns.str.endswith('_y')]

# Renommage des colonnes en enlevant le suffixe `_x`
df_final.columns = df_final.columns.str.replace('_x$', '', regex=True)

In [10]:
df_final.columns

Index(['ID_title', 'title', 'original_title', 'ID_name', 'actor_name', 'actor',
       'actress', 'director', 'original_language', 'release_year',
       'runtime_minutes', 'weighted_averageRating', 'average_rating',
       'numVotes', 'popularity', 'genres', 'Action', 'Adventure', 'Biography',
       'Crime', 'Documentary', 'Fantasy', 'Game-Show', 'Horror', 'Musical',
       'Mystery', 'News', 'Reality-TV', 'Sport', 'Talk-Show', 'Thriller',
       'War', 'Western', 'Animation', 'Comedy', 'Drama', 'Family', 'History',
       'Music', 'Romance', 'ScienceFiction', 'overview', 'poster_path'],
      dtype='object')

In [11]:
# Initialisation d'un dictionnaire pour stocker le nombre de doublons par colonne
duplicate_counts = {}

# Pour chaque colonne du DataFrame
for col in df_final.columns:
    # Utilisation de duplicated() pour détecter les doublons
    num_duplicates = df_final[col].duplicated(keep=False).sum() - df_final[col].duplicated(keep='first').sum()
    duplicate_counts[col] = num_duplicates

# Affichage du nombre de doublons par colonne
for col, count in duplicate_counts.items():
    print(f"Colonne '{col}' a {count} doublons")

Colonne 'ID_title' a 26771 doublons
Colonne 'title' a 26771 doublons
Colonne 'original_title' a 26771 doublons
Colonne 'ID_name' a 47343 doublons
Colonne 'actor_name' a 47660 doublons
Colonne 'actor' a 2 doublons
Colonne 'actress' a 2 doublons
Colonne 'director' a 2 doublons
Colonne 'original_language' a 70 doublons
Colonne 'release_year' a 40 doublons
Colonne 'runtime_minutes' a 148 doublons
Colonne 'weighted_averageRating' a 20081 doublons
Colonne 'average_rating' a 38 doublons
Colonne 'numVotes' a 9995 doublons
Colonne 'popularity' a 2624 doublons
Colonne 'genres' a 629 doublons
Colonne 'Action' a 2 doublons
Colonne 'Adventure' a 2 doublons
Colonne 'Biography' a 2 doublons
Colonne 'Crime' a 2 doublons
Colonne 'Documentary' a 2 doublons
Colonne 'Fantasy' a 2 doublons
Colonne 'Game-Show' a 1 doublons
Colonne 'Horror' a 2 doublons
Colonne 'Musical' a 2 doublons
Colonne 'Mystery' a 2 doublons
Colonne 'News' a 2 doublons
Colonne 'Reality-TV' a 2 doublons
Colonne 'Sport' a 2 doublons
Colonne 'Talk-Show' a 2 doublons
Colonne 'Thriller' a 2 doublons
Colonne 'War' a 2 doublons
Colonne 'Western' a 2 doublons
Colonne 'Animation' a 2 doublons
Colonne 'Comedy' a 2 doublons
Colonne 'Drama' a 2 doublons
Colonne 'Family' a 2 doublons
Colonne 'History' a 2 doublons
Colonne 'Music' a 2 doublons
Colonne 'Romance' a 2 doublons
Colonne 'ScienceFiction' a 2 doublons
Colonne 'overview' a 2898 doublons
Colonne 'poster_path' a 2855 doublons

In [12]:
# Initialisation des comptes de NaN
nan_counts_per_column = {}
total_nan_counts = 0

# Boucle sur chaque colonne et comptage des NaN
for column in df_final.columns:
    nan_count = df_final[column].isna().sum()
    nan_counts_per_column[column] = nan_count
    total_nan_counts += nan_count

# Affichage des résultats
print("Nombre de NaN par colonne:")
for column, count in nan_counts_per_column.items():
    print(f"Colonne {column}: {count} NaN")

Nombre de NaN par colonne:
Colonne ID_title: 0 NaN
Colonne title: 0 NaN
Colonne original_title: 0 NaN
Colonne ID_name: 0 NaN
Colonne actor_name: 0 NaN
Colonne actor: 0 NaN
Colonne actress: 0 NaN
Colonne director: 0 NaN
Colonne original_language: 219978 NaN
Colonne release_year: 0 NaN
Colonne runtime_minutes: 0 NaN
Colonne weighted_averageRating: 0 NaN
Colonne average_rating: 0 NaN
Colonne numVotes: 0 NaN
Colonne popularity: 260982 NaN
Colonne genres: 0 NaN
Colonne Action: 0 NaN
Colonne Adventure: 0 NaN
Colonne Biography: 0 NaN
Colonne Crime: 0 NaN
Colonne Documentary: 0 NaN
Colonne Fantasy: 0 NaN
Colonne Game-Show: 0 NaN
Colonne Horror: 0 NaN
Colonne Musical: 0 NaN
Colonne Mystery: 0 NaN
Colonne News: 0 NaN
Colonne Reality-TV: 0 NaN
Colonne Sport: 0 NaN
Colonne Talk-Show: 0 NaN
Colonne Thriller: 0 NaN
Colonne War: 0 NaN
Colonne Western: 0 NaN
Colonne Animation: 0 NaN
Colonne Comedy: 0 NaN
Colonne Drama: 0 NaN
Colonne Family: 0 NaN
Colonne History: 0 NaN
Colonne Music: 0 NaN
Colonne Romance: 0 NaN
Colonne ScienceFiction: 0 NaN
Colonne overview: 260982 NaN
Colonne poster_path: 263754 NaN

In [13]:
# Supprimer les lignes doublons
df_final = df_final.drop_duplicates()

#  Réinitialiser l'index après suppression des doublons
df_final = df_final.reset_index(drop=True)

In [14]:
print(df_final.info())
print(df_final.sample(2).to_markdown(index=False, numalign="left", stralign="left"))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 251523 entries, 0 to 251522
Data columns (total 43 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   ID_title                251523 non-null  object
 1   title                   251523 non-null  object
 2   original_title          251523 non-null  object
 3   ID_name                 251523 non-null  object
 4   actor_name              251523 non-null  object
 5   actor                   251523 non-null  float64
 6   actress                 251523 non-null  float64
 7   director                251523 non-null  float64
 8   original_language       31545 non-null   object
 9   release_year            251523 non-null  int64
 10  runtime_minutes         251523 non-null  int64
 11  weighted_averageRating  251523 non-null  float64
 12  average_rating          251523 non-null  float64
 13  numVotes                251523 non-null  float64
 14  popularity              27345 non-null   float64
 15  genres                  251523 non-null  object
 16  Action                  251523 non-null  int64
 17  Adventure               251523 non-null  int64
 18  Biography               251523 non-null  int64
 19  Crime                   251523 non-null  int64
 20  Documentary             251523 non-null  int64
 21  Fantasy                 251523 non-null  int64
 22  Game-Show               251523 non-null  int64
 23  Horror                  251523 non-null  int64
 24  Musical                 251523 non-null  int64
 25  Mystery                 251523 non-null  int64
 26  News                    251523 non-null  int64
 27  Reality-TV              251523 non-null  int64
 28  Sport                   251523 non-null  int64
 29  Talk-Show               251523 non-null  int64
 30  Thriller                251523 non-null  int64
 31  War                     251523 non-null  int64
 32  Western                 251523 non-null  int64
 33  Animation               251523 non-null  int64
 34  Comedy                  251523 non-null  int64
 35  Drama                   251523 non-null  int64
 36  Family                  251523 non-null  int64
 37  History                 251523 non-null  int64
 38  Music                   251523 non-null  int64
 39  Romance                 251523 non-null  int64
 40  ScienceFiction          251523 non-null  int64
 41  overview                27345 non-null   object
 42  poster_path             27013 non-null   object
dtypes: float64(7), int64(27), object(9)
memory usage: 82.5+ MB
None
| ID_title   | title                   | original_title      | ID_name   | actor_name   | actor   | actress   | director   | original_language   | release_year   | runtime_minutes   | weighted_averageRating   | average_rating   | numVotes   | popularity   | genres       | Action   | Adventure   | Biography   | Crime   | Documentary   | Fantasy   | Game-Show   | Horror   | Musical   | Mystery   | News   | Reality-TV   | Sport   | Talk-Show   | Thriller   | War   | Western   | Animation   | Comedy   | Drama   | Family   | History   | Music   | Romance   | ScienceFiction   | overview   | poster_path   |
|:-----------|:------------------------|:--------------------|:----------|:-------------|:--------|:----------|:-----------|:--------------------|:---------------|:------------------|:-------------------------|:-----------------|:-----------|:-------------|:-------------|:---------|:------------|:------------|:--------|:--------------|:----------|:------------|:---------|:----------|:----------|:-------|:-------------|:--------|:------------|:-----------|:------|:----------|:------------|:---------|:--------|:---------|:----------|:--------|:----------|:-----------------|:-----------|:--------------|
| tt0158030  | The Girl of Your Dreams | La niña de tus ojos | nm0038572 | Neus Asensi  | 0       | 1         | 0          | nan                 | 1998           | 121               | 6.66781                  | 6.7              | 4532       | nan          | Comedy,Drama | 0        | 0           | 0           | 0       | 0             | 0         | 0           | 0        | 0         | 0         | 0      | 0            | 0       | 0           | 0          | 0     | 0         | 0           | 1        | 1       | 0        | 0         | 0       | 0         | 0                | nan        | nan           |
| tt6588966  | Hichki                  | Hichki              | nm9884033 | Pankaj Anand | 1       | 0         | 0          | nan                 | 2018           | 116               | 7.46989                  | 7.5              | 13927      | nan          | Comedy,Drama | 0        | 0           | 0           | 0       | 0             | 0         | 0           | 0        | 0         | 0         | 0      | 0            | 0       | 0           | 0          | 0     | 0         | 0           | 1        | 1       | 0        | 0         | 0       | 0         | 0                | nan        | nan           |

##### ***Colonne actor_name***

In [15]:
print(df_final['actor_name'].unique())

['Bradley Cooper' 'Sienna Miller' 'Daniel Brühl' ... 'Larry Harvey'
 'Michael Mikel' 'Chicken John']

In [16]:
# 1. Éliminer les crochets et les apostrophes
#mergeTMDBDummiActor['actor_name'] = mergeTMDBDummiActor['actor_name'].str.replace(r'[\[\]\'\"]', '', regex=True)

# # 2. Remplacer les virgules par des points-virgules pour uniformiser
#mergeTMDBDummiActor['actor_name'] = mergeTMDBDummiActor['actor_name'].str.replace(' ', ',')

# 3. Éliminer les espaces superflus au début et à la fin
df_final['actor_name'] = df_final['actor_name'].str.strip()

# 4. Éliminer les espaces supplémentaires entre les mots
#mergeTMDBDummiActor['actor_name'] = mergeTMDBDummiActor['actor_name'].str.replace(r'\s*;\s*', ', ', regex=True)

### ***Selection de Colonne original_language***

In [17]:
# 1. Éliminer les crochets et les apostrophes
#TmdbCleanDumActor_Final['original_language'] = TmdbCleanDumActor_Final['original_language'].str.replace(r'[\[\]\'\"]', '', regex=True)

# # 2. Remplacer les virgules par des points-virgules pour uniformiser
#mergeTMDBDummiActor['actor_name'] = mergeTMDBDummiActor['actor_name'].str.replace(' ', ',')

# 3. Éliminer les espaces superflus au début et à la fin
df_final['original_language'] = df_final['original_language'].str.strip()

# 4. Éliminer les espaces supplémentaires entre les mots
#mergeTMDBDummiActor['actor_name'] = mergeTMDBDummiActor['actor_name'].str.replace(r'\s*;\s*', ', ', regex=True)

In [18]:
df_lang = df_final["original_language"].value_counts()
df_lang

original_language
en    22235
es     1307
fr     1170
de      970
nl      713
      ...
dz        7
as        7
sk        4
ka        4
hy        1
Name: count, Length: 70, dtype: int64

In [19]:
# # Langues à conserver
languages_to_keep = ['en', 'fr', 'es', 'de', 'nl', 'ja', 'it', 'pt', 'da', 'fi','sv', np.nan]

# Filtrage du DataFrame
df_final = df_final[df_final['original_language'].isin(languages_to_keep)]

# Affichage du DataFrame filtré
print(df_final.info())

<class 'pandas.core.frame.DataFrame'>
Index: 248046 entries, 0 to 251522
Data columns (total 43 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   ID_title                248046 non-null  object
 1   title                   248046 non-null  object
 2   original_title          248046 non-null  object
 3   ID_name                 248046 non-null  object
 4   actor_name              248046 non-null  object
 5   actor                   248046 non-null  float64
 6   actress                 248046 non-null  float64
 7   director                248046 non-null  float64
 8   original_language       28068 non-null   object
 9   release_year            248046 non-null  int64
 10  runtime_minutes         248046 non-null  int64
 11  weighted_averageRating  248046 non-null  float64
 12  average_rating          248046 non-null  float64
 13  numVotes                248046 non-null  float64
 14  popularity              25109 non-null   float64
 15  genres                  248046 non-null  object
 16  Action                  248046 non-null  int64
 17  Adventure               248046 non-null  int64
 18  Biography               248046 non-null  int64
 19  Crime                   248046 non-null  int64
 20  Documentary             248046 non-null  int64
 21  Fantasy                 248046 non-null  int64
 22  Game-Show               248046 non-null  int64
 23  Horror                  248046 non-null  int64
 24  Musical                 248046 non-null  int64
 25  Mystery                 248046 non-null  int64
 26  News                    248046 non-null  int64
 27  Reality-TV              248046 non-null  int64
 28  Sport                   248046 non-null  int64
 29  Talk-Show               248046 non-null  int64
 30  Thriller                248046 non-null  int64
 31  War                     248046 non-null  int64
 32  Western                 248046 non-null  int64
 33  Animation               248046 non-null  int64
 34  Comedy                  248046 non-null  int64
 35  Drama                   248046 non-null  int64
 36  Family                  248046 non-null  int64
 37  History                 248046 non-null  int64
 38  Music                   248046 non-null  int64
 39  Romance                 248046 non-null  int64
 40  ScienceFiction          248046 non-null  int64
 41  overview                25109 non-null   object
 42  poster_path             24805 non-null   object
dtypes: float64(7), int64(27), object(9)
memory usage: 83.3+ MB
None

In [20]:
df_final['original_language'].value_counts()

original_language
en    22235
es     1307
fr     1170
de      970
nl      713
ja      670
pt      322
it      259
sv      179
da      123
fi      120
Name: count, dtype: int64

In [21]:
nan_lang = df_final[df_final['original_language'].isnull()]
nan_lang.sample()

,ID_title,title,original_title,ID_name,actor_name,actor,actress,director,original_language,release_year,...,Animation,Comedy,Drama,Family,History,Music,Romance,ScienceFiction,overview,poster_path
240996,tt1342403,Toys in the Attic,Na pude aneb Kdo má dneska narozeniny?,nm3432684,Emily Ricks Hahn,0.00,1.00,0.00,NaN,2009,...,1,0,0,1,0,0,0,0,NaN,NaN

In [22]:
## Remplacer les Nan dans la colonne original_language des films de Tom Hanks
df_final.loc[(df_final['actor_name'] == 'Tom Hanks') & 
                            (df_final['original_language'].isna()), 'original_language'] = 'en'

In [23]:
df_final = df_final.dropna(subset='original_language')

df_final.info()

print(df_final.sample(2).to_markdown(index=False, numalign="left", stralign="left"))

<class 'pandas.core.frame.DataFrame'>
Index: 28091 entries, 0 to 251515
Data columns (total 43 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ID_title                28091 non-null  object
 1   title                   28091 non-null  object
 2   original_title          28091 non-null  object
 3   ID_name                 28091 non-null  object
 4   actor_name              28091 non-null  object
 5   actor                   28091 non-null  float64
 6   actress                 28091 non-null  float64
 7   director                28091 non-null  float64
 8   original_language       28091 non-null  object
 9   release_year            28091 non-null  int64
 10  runtime_minutes         28091 non-null  int64
 11  weighted_averageRating  28091 non-null  float64
 12  average_rating          28091 non-null  float64
 13  numVotes                28091 non-null  float64
 14  popularity              25109 non-null  float64
 15  genres                  28091 non-null  object
 16  Action                  28091 non-null  int64
 17  Adventure               28091 non-null  int64
 18  Biography               28091 non-null  int64
 19  Crime                   28091 non-null  int64
 20  Documentary             28091 non-null  int64
 21  Fantasy                 28091 non-null  int64
 22  Game-Show               28091 non-null  int64
 23  Horror                  28091 non-null  int64
 24  Musical                 28091 non-null  int64
 25  Mystery                 28091 non-null  int64
 26  News                    28091 non-null  int64
 27  Reality-TV              28091 non-null  int64
 28  Sport                   28091 non-null  int64
 29  Talk-Show               28091 non-null  int64
 30  Thriller                28091 non-null  int64
 31  War                     28091 non-null  int64
 32  Western                 28091 non-null  int64
 33  Animation               28091 non-null  int64
 34  Comedy                  28091 non-null  int64
 35  Drama                   28091 non-null  int64
 36  Family                  28091 non-null  int64
 37  History                 28091 non-null  int64
 38  Music                   28091 non-null  int64
 39  Romance                 28091 non-null  int64
 40  ScienceFiction          28091 non-null  int64
 41  overview                25109 non-null  object
 42  poster_path             24805 non-null  object
dtypes: float64(7), int64(27), object(9)
memory usage: 9.4+ MB
| ID_title   | title               | original_title      | ID_name   | actor_name   | actor   | actress   | director   | original_language   | release_year   | runtime_minutes   | weighted_averageRating   | average_rating   | numVotes   | popularity   | genres                 | Action   | Adventure   | Biography   | Crime   | Documentary   | Fantasy   | Game-Show   | Horror   | Musical   | Mystery   | News   | Reality-TV   | Sport   | Talk-Show   | Thriller   | War   | Western   | Animation   | Comedy   | Drama   | Family   | History   | Music   | Romance   | ScienceFiction   | overview                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               | poster_path                      |
|:-----------|:--------------------|:--------------------|:----------|:-------------|:--------|:----------|:-----------|:--------------------|:---------------|:------------------|:-------------------------|:-----------------|:-----------|:-------------|:-----------------------|:---------|:------------|:------------|:--------|:--------------|:----------|:------------|:---------|:----------|:----------|:-------|:-------------|:--------|:------------|:-----------|:------|:----------|:------------|:---------|:--------|:---------|:----------|:--------|:----------|:-----------------|:-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:---------------------------------|
| tt6450186  | I Can Only Imagine  | I Can Only Imagine  | nm0000598 | Dennis Quaid | 1       | 0         | 0          | en                  | 2018           | 110               | 7.28081                  | 7.3              | 18499      | 25.93        | Biography,Drama,Family | 0        | 0           | 1           | 0       | 0             | 0         | 0           | 0        | 0         | 0         | 0      | 0            | 0       | 0           | 0          | 0     | 0         | 0           | 0        | 1       | 1        | 0         | 0       | 0         | 0                | 10-year-old Bart Millard lives with his mother and abusive father Arthur in Texas. One day his mother drops him off at a Christian camp where he meets Shannon. Upon his return from camp, Bart finds his mother has left and movers are removing her belongings. He angrily confronts his father, who denies that his abusiveness was the reason she left. Years later, in high school, Bart and Shannon are dating. Bart plays football to please his father but is injured, breaking both ankles and ending his career. The only elective with openings is music class, so he reluctantly signs up. | /veZszwMZu8d3WMU6TJX9sV5w1Y4.jpg |
| tt4669788  | On the Basis of Sex | On the Basis of Sex | nm2309517 | Armie Hammer | 1       | 0         | 0          | en                  | 2018           | 120               | 7.0925                   | 7.1              | 38779      | 14.168       | Biography,Drama        | 0        | 0           | 1           | 0       | 0             | 0         | 0           | 0        | 0         | 0         | 0      | 0            | 0       | 0           | 0          | 0     | 0         | 0           | 0        | 1       | 0        | 0         | 0       | 0         | 0                | Young lawyer Ruth Bader Ginsburg teams with her husband Marty to bring a groundbreaking case before the U.S. Court of Appeals and overturn a century of sex discrimination.                                                                                                                                                                                                                                                                                                                                                                                                                            | /izY9Le3QWtu7xkHq7bjJnuE5yGI.jpg |

#### ***Selection des TOP acteurs/actrices***

In [24]:
# Filtrer les colonnes nécessaires
df_filtered = df_final[['ID_name', 'actor_name', 'weighted_averageRating']]

# Calculer la moyenne pondérée et le nombre de films pour chaque acteur
average_ratings = df_filtered.groupby('ID_name').agg(
    average_weighted_rating=('weighted_averageRating', 'mean'),  # Calculer la moyenne pondérée
    actor_name=('actor_name', 'first'),                          # Prendre le premier acteur associé à l'ID_name
    number_of_films=('actor_name', 'size')                       # Compter le nombre de films
).reset_index()

# Réorganiser les colonnes : 
average_ratings = average_ratings[['ID_name', 'actor_name', 'average_weighted_rating', 'number_of_films']]

In [25]:
average_ratings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19657 entries, 0 to 19656
Data columns (total 4 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ID_name                  19657 non-null  object
 1   actor_name               19657 non-null  object
 2   average_weighted_rating  19657 non-null  float64
 3   number_of_films          19657 non-null  int64
dtypes: float64(1), int64(1), object(2)
memory usage: 614.4+ KB

In [29]:
# Trier le DataFrame par 'number_of_films' en ordre décroissant
average_ratings_sorted = average_ratings.sort_values(by='number_of_films', ascending=False)

# Prendre un échantillon de ... lignes du DataFrame trié et l'afficher en format markdown
print(average_ratings_sorted.head(50).to_markdown(index=False, numalign="left", stralign="left"))

| ID_name   | actor_name             | average_weighted_rating   | number_of_films   |
|:----------|:-----------------------|:--------------------------|:------------------|
| nm0000158 | Tom Hanks              | 7.28594                   | 39                |
| nm0000437 | Woody Harrelson        | 6.99267                   | 23                |
| nm0842770 | Tilda Swinton          | 6.96663                   | 21                |
| nm0000353 | Willem Dafoe           | 7.14699                   | 20                |
| nm0799777 | J.K. Simmons           | 7.09251                   | 20                |
| nm0000151 | Morgan Freeman         | 7.21369                   | 20                |
| nm0000354 | Matt Damon             | 7.3345                    | 19                |
| nm0005351 | Ryan Reynolds          | 6.81954                   | 19                |
| nm0631490 | Bill Nighy             | 7.02069                   | 18                |
| nm0748620 | Paul Rudd              | 6.95382                   | 18                |
| nm0000288 | Christian Bale         | 7.41071                   | 17                |
| nm0000949 | Cate Blanchett         | 7.29927                   | 17                |
| nm1209966 | Oscar Isaac            | 6.97003                   | 16                |
| nm0000168 | Samuel L. Jackson      | 7.41793                   | 16                |
| nm0915208 | Naomi Watts            | 6.8585                    | 16                |
| nm0000160 | Ethan Hawke            | 7.35807                   | 16                |
| nm0252961 | Idris Elba             | 6.97226                   | 15                |
| nm0425005 | Dwayne Johnson         | 6.73242                   | 15                |
| nm0330687 | Joseph Gordon-Levitt   | 7.20883                   | 15                |
| nm0000246 | Bruce Willis           | 6.9857                    | 15                |
| nm0000173 | Nicole Kidman          | 6.83369                   | 15                |
| nm0931329 | Michelle Williams      | 7.16826                   | 15                |
| nm0176869 | Steve Coogan           | 6.72575                   | 15                |
| nm0000553 | Liam Neeson            | 7.14839                   | 15                |
| nm0749263 | Mark Ruffalo           | 7.44424                   | 15                |
| nm0000093 | Brad Pitt              | 7.41217                   | 15                |
| nm0165101 | Patricia Clarkson      | 6.90819                   | 15                |
| nm0136797 | Steve Carell           | 7.05111                   | 15                |
| nm0001057 | Toni Collette          | 6.88938                   | 14                |
| nm1212722 | Benedict Cumberbatch   | 7.23372                   | 14                |
| nm0000242 | Mark Wahlberg          | 6.96285                   | 14                |
| nm0000146 | Ralph Fiennes          | 7.31327                   | 14                |
| nm0736622 | Seth Rogen             | 6.9345                    | 14                |
| nm0000285 | Alec Baldwin           | 6.9868                    | 14                |
| nm1297015 | Emma Stone             | 7.11983                   | 14                |
| nm0001132 | Judi Dench             | 6.93863                   | 14                |
| nm0202966 | Keith David            | 7.02119                   | 14                |
| nm1706767 | Jonah Hill             | 7.13975                   | 14                |
| nm1567113 | Jessica Chastain       | 7.15141                   | 14                |
| nm0001570 | Edward Norton          | 7.03863                   | 14                |
| nm0005458 | Jason Statham          | 6.8633                    | 14                |
| nm0005212 | Ian McKellen           | 7.49797                   | 13                |
| nm0352778 | Bill Hader             | 6.68851                   | 13                |
| nm0000701 | Kate Winslet           | 7.05014                   | 13                |
| nm0757855 | Zoe Saldana            | 7.22214                   | 13                |
| nm0350453 | Jake Gyllenhaal        | 7.37529                   | 13                |
| nm0000234 | Charlize Theron        | 6.95902                   | 13                |
| nm0004874 | Vin Diesel             | 7.14534                   | 13                |
| nm0000450 | Philip Seymour Hoffman | 7.32028                   | 13                |
| nm0000191 | Ewan McGregor          | 7.15217                   | 13                |

In [30]:
# Compter le nombre d'acteurs uniques
unique_actor_count = len(average_ratings_sorted['actor_name'].unique())
print(unique_actor_count)

19634

In [31]:
average_ratings_sorted.describe()

       average_weighted_rating  number_of_films
count                 19657.00         19657.00
mean                      6.80             1.43
std                       0.44             1.41
min                       6.25             1.00
25%                       6.45             1.00
50%                       6.70             1.00
75%                       7.06             1.00
max                       9.00            39.00

In [ ]:
# # Initialisation des comptes de NaN
# nan_counts_per_column = {}
# total_nan_counts = 0

# # Boucle sur chaque colonne et comptage des NaN
# for column in mergeTMDBDummiActor.columns:
#     nan_count = mergeTMDBDummiActor[column].isna().sum()
#     nan_counts_per_column[column] = nan_count
#     total_nan_counts += nan_count

# # Affichage des résultats
# print("Nombre de NaN par colonne:")
# for column, count in nan_counts_per_column.items():
#     print(f"Colonne {column}: {count} NaN")

In [34]:
# Filtrer pour obtenir uniquement les ID_name où 'number_of_films' est sup à une certaine valeur 
filtered_id_names = average_ratings[average_ratings['number_of_films'] > 3]['ID_name']

In [36]:
# Convertir le résultat en liste (si nécessaire)
id_name_list = filtered_id_names.tolist()
len(id_name_list)

972

In [37]:
# Récupérer les lignes du DataFrame TmdbCleanDumActor_Final où ID_name est dans id_name_list
filtered_df2 = df_final[TmdbCleanDumActor_Final['ID_name'].isin(id_name_list)]
filtered_df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6214 entries, 0 to 251508
Data columns (total 43 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ID_title                6214 non-null   object
 1   title                   6214 non-null   object
 2   original_title          6214 non-null   object
 3   ID_name                 6214 non-null   object
 4   actor_name              6214 non-null   object
 5   actor                   6214 non-null   float64
 6   actress                 6214 non-null   float64
 7   director                6214 non-null   float64
 8   original_language       6214 non-null   object
 9   release_year            6214 non-null   int64
 10  runtime_minutes         6214 non-null   int64
 11  weighted_averageRating  6214 non-null   float64
 12  average_rating          6214 non-null   float64
 13  numVotes                6214 non-null   float64
 14  popularity              5641 non-null   float64
 15  genres                  6214 non-null   object
 16  Action                  6214 non-null   int64
 17  Adventure               6214 non-null   int64
 18  Biography               6214 non-null   int64
 19  Crime                   6214 non-null   int64
 20  Documentary             6214 non-null   int64
 21  Fantasy                 6214 non-null   int64
 22  Game-Show               6214 non-null   int64
 23  Horror                  6214 non-null   int64
 24  Musical                 6214 non-null   int64
 25  Mystery                 6214 non-null   int64
 26  News                    6214 non-null   int64
 27  Reality-TV              6214 non-null   int64
 28  Sport                   6214 non-null   int64
 29  Talk-Show               6214 non-null   int64
 30  Thriller                6214 non-null   int64
 31  War                     6214 non-null   int64
 32  Western                 6214 non-null   int64
 33  Animation               6214 non-null   int64
 34  Comedy                  6214 non-null   int64
 35  Drama                   6214 non-null   int64
 36  Family                  6214 non-null   int64
 37  History                 6214 non-null   int64
 38  Music                   6214 non-null   int64
 39  Romance                 6214 non-null   int64
 40  ScienceFiction          6214 non-null   int64
 41  overview                5641 non-null   object
 42  poster_path             5634 non-null   object
dtypes: float64(7), int64(27), object(9)
memory usage: 2.1+ MB

C:\Users\titgr\AppData\Local\Temp\ipykernel_8848\1538800203.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  filtered_df2 = df_final[TmdbCleanDumActor_Final['ID_name'].isin(id_name_list)]

### Dummies

In [38]:
# Creating dummy variables from the 'actor_name' column
df_dum2 = pd.get_dummies(filtered_df2['actor_name'])

# Concaténer les variables factices au DataFrame d'origine (facultatif)
df = pd.concat([filtered_df2, df_dum2], axis=1)

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6214 entries, 0 to 251508
Columns: 1015 entries, ID_title to Zoë Kravitz
dtypes: bool(972), float64(7), int64(27), object(9)
memory usage: 7.8+ MB

In [49]:
# Boucle pour imprimer chaque colonne et son type de données
for column, dtype in df.dtypes.items():
    print(f'{column}: {dtype}')

ID_title: object
title: object
original_title: object
ID_name: object
actor_name: object
actor: float64
actress: float64
director: float64
original_language: object
release_year: int64
runtime_minutes: int64
weighted_averageRating: float64
average_rating: float64
numVotes: float64
popularity: float64
genres: object
Action: int64
Adventure: int64
Biography: int64
Crime: int64
Documentary: int64
Fantasy: int64
Game-Show: int64
Horror: int64
Musical: int64
Mystery: int64
News: int64
Reality-TV: int64
Sport: int64
Talk-Show: int64
Thriller: int64
War: int64
Western: int64
Animation: int64
Comedy: int64
Drama: int64
Family: int64
History: int64
Music: int64
Romance: int64
ScienceFiction: int64
overview: object
poster_path: object
Aaron Eckhart: int32
Aaron Paul: int32
Aasif Mandvi: int32
Abbie Cornish: int32
Abby Quinn: int32
Abby Ryder Fortson: int32
Abigail Breslin: int32
Adam Brody: int32
Adam Driver: int32
Adam Sandler: int32
Adam Scott: int32
Adeel Akhtar: int32
Adriane Lenox: int32
Adèle Haenel: int32
Akio Ôtsuka: int32
Al Pacino: int32
Alan Arkin: int32
Alan Cumming: int32
Alan Rickman: int32
Alan Tudyk: int32
Albert Brooks: int32
Alec Baldwin: int32
Alessandro Nivola: int32
Alex Wolff: int32
Alexandra Maria Lara: int32
Alexandra Shipp: int32
Alfre Woodard: int32
Alfred Molina: int32
Alice Braga: int32
Alice Krige: int32
Alice Lowe: int32
Alicia Vikander: int32
Alicia Witt: int32
Alison Brie: int32
Alison Pill: int32
Allison Janney: int32
Amanda Peet: int32
Amanda Seyfried: int32
Amber Heard: int32
Amy Adams: int32
Amy Landecker: int32
Amy Poehler: int32
Amy Ryan: int32
Amy Seimetz: int32
Andrea Riseborough: int32
Andrew Garfield: int32
Andrew Scott: int32
Andy Nyman: int32
Andy Samberg: int32
Andy Serkis: int32
Angela Bassett: int32
Angelina Jolie: int32
Angourie Rice: int32
Anika Noni Rose: int32
Ann Dowd: int32
Anna Faris: int32
Anna Kendrick: int32
Anna Paquin: int32
AnnaSophia Robb: int32
Anne Hathaway: int32
Anneke Blok: int32
Annette Bening: int32
Annie Potts: int32
Anthony Daniels: int32
Anthony Edwards: int32
Anthony Hopkins: int32
Anthony Mackie: int32
Anton Yelchin: int32
Antonia Zegers: int32
Antonio Banderas: int32
Antonio de la Torre: int32
Anya Taylor-Joy: int32
Armie Hammer: int32
Armin Mueller-Stahl: int32
Arnold Schwarzenegger: int32
Asa Butterfield: int32
Ashley Judd: int32
Aubrey Plaza: int32
Audrey Tautou: int32
August Diehl: int32
Awkwafina: int32
Barry Atsma: int32
Barry Keoghan: int32
Beau Knapp: int32
Becky Ann Baker: int32
Ben Affleck: int32
Ben Daniels: int32
Ben Foster: int32
Ben Kingsley: int32
Ben Mendelsohn: int32
Ben Stiller: int32
Ben Whishaw: int32
Benedict Cumberbatch: int32
Benedict Wong: int32
Benicio Del Toro: int32
Benito Martinez: int32
Benjamin Bratt: int32
Bernie Mac: int32
Beth Grant: int32
Bill Camp: int32
Bill Cobbs: int32
Bill Hader: int32
Bill Murray: int32
Bill Nighy: int32
Bill Paxton: int32
Bill Pullman: int32
Bill Skarsgård: int32
Billy Bob Thornton: int32
Billy Boyd: int32
Billy Crudup: int32
Birgit Minichmayr: int32
Blake Jenner: int32
Blake Lively: int32
Bob Balaban: int32
Bob Gunton: int32
Bobby Cannavale: int32
Bobby Moynihan: int32
Bonnie Hunt: int32
Brad Pitt: int32
Bradley Cooper: int32
Bradley Whitford: int32
Brendan Gleeson: int32
Brian Cox: int32
Brian Tyree Henry: int32
Brian d'Arcy James: int32
Brie Larson: int32
Britt Robertson: int32
Bruce Altman: int32
Bruce Dern: int32
Bruce Greenwood: int32
Bruce McGill: int32
Bruce Willis: int32
Bruno Ganz: int32
Bryan Cranston: int32
Bryce Dallas Howard: int32
Brían F. O'Byrne: int32
Burn Gorman: int32
Bárbara Lennie: int32
Caleb Landry Jones: int32
Cameron Diaz: int32
Cara Seymour: int32
Carey Mulligan: int32
Carice van Houten: int32
Carla Gugino: int32
Carrie Preston: int32
Cary-Hiroyuki Tagawa: int32
Casey Affleck: int32
Cate Blanchett: int32
Catherine Keener: int32
Catherine O'Hara: int32
Catherine Zeta-Jones: int32
Celia Imrie: int32
Chadwick Boseman: int32
Channing Tatum: int32
Charles Dance: int32
Charlie Hunnam: int32
Charlie Plummer: int32
Charlie Tahan: int32
Charlize Theron: int32
Charlotte Gainsbourg: int32
Charlotte Rampling: int32
Chiwetel Ejiofor: int32
Chloë Grace Moretz: int32
Chloë Sevigny: int32
Chris Cooper: int32
Chris Evans: int32
Chris Hemsworth: int32
Chris Messina: int32
Chris Mulkey: int32
Chris O'Dowd: int32
Chris Pine: int32
Chris Pratt: int32
Christian Bale: int32
Christian McKay: int32
Christian Slater: int32
Christina Ricci: int32
Christoph Waltz: int32
Christopher Abbott: int32
Christopher Lee: int32
Christopher McDonald: int32
Christopher Mintz-Plasse: int32
Christopher Plummer: int32
Christopher Walken: int32
Ciarán Hinds: int32
Cillian Murphy: int32
Clancy Brown: int32
Clark Gregg: int32
Clarke Peters: int32
Clayne Crawford: int32
Cliff Curtis: int32
Clifton Collins Jr.: int32
Clint Eastwood: int32
Clive Owen: int32
Cloris Leachman: int32
Cole Hauser: int32
Colin Farrell: int32
Colin Firth: int32
Colm Feore: int32
Colm Meaney: int32
Colman Domingo: int32
Common: int32
Connie Britton: int32
Connie Nielsen: int32
Constance Wu: int32
Corey Johnson: int32
Corey Stoll: int32
Craig Robinson: int32
Da'Vine Joy Randolph: int32
Daisy Ridley: int32
Dakota Fanning: int32
Damián Alcázar: int32
Daniel Brühl: int32
Daniel Craig: int32
Daniel Henshall: int32
Daniel Mays: int32
Daniel Radcliffe: int32
Danielle Macdonald: int32
Danny DeVito: int32
Danny Glover: int32
Danny Huston: int32
Danny McBride: int32
Daryl Hannah: int32
Dave Bautista: int32
Dave Franco: int32
David Cross: int32
David Dastmalchian: int32
David Hyde Pierce: int32
David Krumholtz: int32
David Morse: int32
David Oyelowo: int32
David Strathairn: int32
David Thewlis: int32
David Wenham: int32
Denis Leary: int32
Dennis Haysbert: int32
Dennis Quaid: int32
Denzel Washington: int32
Derek Jacobi: int32
Derek Luke: int32
Dermot Mulroney: int32
Dev Patel: int32
Devid Striesow: int32
Diane Kruger: int32
Diane Lane: int32
Dianne Wiest: int32
Diego Luna: int32
Djimon Hounsou: int32
Dolph Lundgren: int32
Domhnall Gleeson: int32
Dominic Cooper: int32
Dominic West: int32
Don Cheadle: int32
Donald Sutherland: int32
Douglas Booth: int32
Dustin Hoffman: int32
Dwayne Johnson: int32
Dylan Baker: int32
Ed Harris: int32
Ed Helms: int32
Ed Skrein: int32
Eddie Marsan: int32
Eddie Murphy: int32
Eddie Redmayne: int32
Eduard Fernández: int32
Edward Asner: int32
Edward Norton: int32
Elena Anaya: int32
Elijah Wood: int32
Elisabeth Shue: int32
Elizabeth Banks: int32
Elizabeth Olsen: int32
Elle Fanning: int32
Ellen Burstyn: int32
Elliot Page: int32
Emile Hirsch: int32
Emily Blunt: int32
Emily Mortimer: int32
Emily Watson: int32
Emma Roberts: int32
Emma Stone: int32
Emma Thompson: int32
Emma Watson: int32
Emory Cohen: int32
Eric Bana: int32
Essie Davis: int32
Ethan Hawke: int32
Eugene Levy: int32
Eva Birthistle: int32
Eva Green: int32
Evan Peters: int32
Evan Rachel Wood: int32
Ewan McGregor: int32
Famke Janssen: int32
Fedja van Huêt: int32
Felicity Jones: int32
Fernando Becerril: int32
Filip Peeters: int32
Finn Wolfhard: int32
Fionnula Flanagan: int32
Florence Pugh: int32
Forest Whitaker: int32
Frances Fisher: int32
Frances McDormand: int32
Frank Grillo: int32
Frank Lammers: int32
François Damiens: int32
Fred Melamed: int32
Fred Willard: int32
Freddie Highmore: int32
Freida Pinto: int32
Gabriel Byrne: int32
Gal Gadot: int32
Garret Dillahunt: int32
Garrett Hedlund: int32
Gary Cole: int32
Gary Oldman: int32
Gemma Arterton: int32
Gena Rowlands: int32
Geoffrey Rush: int32
Georg Friedrich: int32
George Clooney: int32
George MacKay: int32
Geraldine Somerville: int32
Gerard Butler: int32
Giancarlo Esposito: int32
Gina Gershon: int32
Giovanni Ribisi: int32
Glen Powell: int32
Glenn Close: int32
Golshifteh Farahani: int32
Graham Greene: int32
Graham McTavish: int32
Greg Kinnear: int32
Gugu Mbatha-Raw: int32
Guy Pearce: int32
Gwyneth Paltrow: int32
Hailee Steinfeld: int32
Hal Holbrook: int32
Haley Bennett: int32
Halle Berry: int32
Harold Perrineau: int32
Harris Dickinson: int32
Harrison Ford: int32
Harry Connick Jr.: int32
Harry Melling: int32
Harvey Keitel: int32
Hayley Atwell: int32
Healthy Emmie: int32
Heath Ledger: int32
Helen Mirren: int32
Helena Bonham Carter: int32
Henry Goodman: int32
Hilary Swank: int32
Holly Hunter: int32
Hugh Bonneville: int32
Hugh Dancy: int32
Hugh Grant: int32
Hugh Jackman: int32
Hugh Laurie: int32
Hugo Weaving: int32
Ian Hart: int32
Ian Holm: int32
Ian McElhinney: int32
Ian McKellen: int32
Ian McShane: int32
Idris Elba: int32
Imelda Staunton: int32
Imogen Poots: int32
Inma Cuesta: int32
Irrfan Khan: int32
Isabelle Huppert: int32
Isiah Whitlock Jr.: int32
Isla Fisher: int32
J.K. Simmons: int32
J.T. Walsh: int32
Jaap Spijkers: int32
Jack Black: int32
Jack Davenport: int32
Jack Dylan Grazer: int32
Jack Huston: int32
Jack Nicholson: int32
Jacki Weaver: int32
Jackie Chan: int32
Jackie Earle Haley: int32
Jaeden Martell: int32
Jai Courtney: int32
Jaime Lyn Beatty: int32
Jake Gyllenhaal: int32
James Badge Dale: int32
James Caan: int32
James Cromwell: int32
James Faulkner: int32
James Franco: int32
James Marsden: int32
James McAvoy: int32
James Nesbitt: int32
Jamie Foxx: int32
Jane Adams: int32
Jane Alexander: int32
Jared Leto: int32
Jason Bateman: int32
Jason Clarke: int32
Jason Flemyng: int32
Jason Isaacs: int32
Jason Mitchell: int32
Jason Ritter: int32
Jason Schwartzman: int32
Jason Segel: int32
Jason Statham: int32
Jason Sudeikis: int32
Jasper Pääkkönen: int32
Javier Bardem: int32
Jay Baruchel: int32
Jayme Lawson: int32
Jean Reno: int32
Jean-Pierre Darroussin: int32
Jeff Bridges: int32
Jeff Daniels: int32
Jeffrey Donovan: int32
Jeffrey Tambor: int32
Jeffrey Wright: int32
Jena Malone: int32
Jennifer Aniston: int32
Jennifer Connelly: int32
Jennifer Ehle: int32
Jennifer Garner: int32
Jennifer Jason Leigh: int32
Jennifer Lawrence: int32
Jennifer Saunders: int32
Jenny Slate: int32
Jensen Ackles: int32
Jeremy Irons: int32
Jeremy Renner: int32
Jeremy Shamos: int32
Jeremy Sisto: int32
Jeremy Strong: int32
Jesse Eisenberg: int32
Jesse Plemons: int32
Jessica Biel: int32
Jessica Chastain: int32
Jim Belushi: int32
Jim Broadbent: int32
Jim Carrey: int32
Jim Caviezel: int32
Jim Cummings: int32
Jim Gaffigan: int32
Joan Allen: int32
Joan Cusack: int32
Joanna Lumley: int32
Joaquin Phoenix: int32
Jodie Foster: int32
Joe Cole: int32
Joel Edgerton: int32
Joel Kinnaman: int32
Joey King: int32
Johan Heldenbergh: int32
John Boyega: int32
John C. Reilly: int32
John Carroll Lynch: int32
John Cena: int32
John Cho: int32
John Cleese: int32
John Corbett: int32
John Cusack: int32
John DiMaggio: int32
John Gallagher Jr.: int32
John Goodman: int32
John Hannah: int32
John Hawkes: int32
John Krasinski: int32
John Leguizamo: int32
John Lithgow: int32
John Magaro: int32
John Mahoney: int32
John Malkovich: int32
John Ortiz: int32
John Ratzenberger: int32
John Sessions: int32
John Travolta: int32
John Turturro: int32
Johnny Depp: int32
Johnny Flynn: int32
Jon Bernthal: int32
Jon Favreau: int32
Jon Hamm: int32
Jon Voight: int32
Jonah Hill: int32
Jonathan Banks: int32
Jonathan Pryce: int32
Jonny Lee Miller: int32
Jordana Brewster: int32
Josef Hader: int32
Joseph Gordon-Levitt: int32
Joseph Mazzello: int32
Josh Brolin: int32
Josh Duhamel: int32
Josh Gad: int32
Josh Hamilton: int32
Josh Hartnett: int32
Josh Hutcherson: int32
Josh Lucas: int32
Josh Pais: int32
Josh Peck: int32
Jude Law: int32
Judi Dench: int32
Judy Greer: int32
Julia Ormond: int32
Julia Roberts: int32
Julia Stiles: int32
Julianne Moore: int32
Julie Delpy: int32
Julie Walters: int32
Juliette Lewis: int32
Justice Smith: int32
Justin Bartha: int32
Justin Long: int32
Justin Timberlake: int32
Jérémie Renier: int32
Jürgen Vogel: int32
Kaitlyn Dever: int32
Karan Soni: int32
Karen Gillan: int32
Karina Smulders: int32
Karl Urban: int32
Karra Elejalde: int32
Kat Dennings: int32
Kate Beckinsale: int32
Kate Mara: int32
Kate McKinnon: int32
Kate Winslet: int32
Katherine Waterston: int32
Kathryn Hahn: int32
Kathy Baker: int32
Kathy Bates: int32
Katie Holmes: int32
Kaya Scodelario: int32
Keanu Reeves: int32
Keegan-Michael Key: int32
Keira Knightley: int32
Keisha Castle-Hughes: int32
Keith David: int32
Keke Palmer: int32
Kelly Macdonald: int32
Ken Jeong: int32
Ken Watanabe: int32
Kenneth Branagh: int32
Keri Russell: int32
Kerry Condon: int32
Kevin Corrigan: int32
Kevin Costner: int32
Kevin Hart: int32
Kevin McNally: int32
Kevin Spacey: int32
Ki Hong Lee: int32
Kiefer Sutherland: int32
Kieran Culkin: int32
Kirsten Dunst: int32
Kodi Smit-McPhee: int32
Kris Kristofferson: int32
Kristen Bell: int32
Kristen Stewart: int32
Kristen Wiig: int32
Kristin Scott Thomas: int32
Kurt Russell: int32
Kyle Chandler: int32
Lake Bell: int32
Lance Reddick: int32
Laura Harrier: int32
Laura Linney: int32
Lauren Ambrose: int32
Lauren Graham: int32
Laurence Fishburne: int32
Laurie Metcalf: int32
Lena Headey: int32
Leonardo DiCaprio: int32
Leonardo Sbaraglia: int32
Lesley Manville: int32
Leslie Mann: int32
Liam Neeson: int32
Liev Schreiber: int32
Lil Rel Howery: int32
Lily Collins: int32
Lily James: int32
Linus Roache: int32
Lisa Kudrow: int32
Logan Lerman: int32
Lois Smith: int32
Lou Taylor Pucci: int32
Louis C.K.: int32
Louisa Krause: int32
Lucas Black: int32
Lucas Hedges: int32
Lucy Liu: int32
Ludacris: int32
Luis Tosar: int32
Luke Evans: int32
Luke Kirby: int32
Luke Wilson: int32
Lynn Collins: int32
Léa Seydoux: int32
Mackenzie Crook: int32
Macon Blair: int32
Mads Mikkelsen: int32
Maggie Gyllenhaal: int32
Mahershala Ali: int32
Manolo Solo: int32
Manuel Garcia-Rulfo: int32
Marcel Hensema: int32
Marcia Gay Harden: int32
Margaret Qualley: int32
Margo Martindale: int32
Margot Robbie: int32
Maria Bello: int32
Maria Doyle Kennedy: int32
Marion Cotillard: int32
Marisa Tomei: int32
Mark Boone Junior: int32
Mark Duplass: int32
Mark Hamill: int32
Mark Ruffalo: int32
Mark Rylance: int32
Mark Strong: int32
Mark Wahlberg: int32
Mark Webber: int32
Martin Freeman: int32
Martin Sheen: int32
Martin Short: int32
Martina Gedeck: int32
Marwan Kenzari: int32
Mary Steenburgen: int32
Mary-Louise Parker: int32
Mathieu Amalric: int32
Matt Bomer: int32
Matt Damon: int32
Matt Nable: int32
Matt Smith: int32
Matthew Goode: int32
Matthew Macfadyen: int32
Matthew Maher: int32
Matthew McConaughey: int32
Matthew Mercer: int32
Matthew Modine: int32
Matthias Schoenaerts: int32
Matthias Schweighöfer: int32
Max Mauff: int32
Max Minghella: int32
Maya Rudolph: int32
Mel Gibson: int32
Melissa Leo: int32
Melissa McCarthy: int32
Meredith Hagner: int32
Meryl Streep: int32
Mia Wasikowska: int32
Michael Angarano: int32
Michael Caine: int32
Michael Cera: int32
Michael Chernus: int32
Michael Clarke Duncan: int32
Michael Douglas: int32
Michael Fassbender: int32
Michael Gambon: int32
Michael J. Fox: int32
Michael Keaton: int32
Michael Kelly: int32
Michael Kenneth Williams: int32
Michael McElhatton: int32
Michael Peña: int32
Michael Rapaport: int32
Michael Rispoli: int32
Michael Shannon: int32
Michael Sheen: int32
Michael Stuhlbarg: int32
Michael Wincott: int32
Michelle Fairley: int32
Michelle Monaghan: int32
Michelle Rodriguez: int32
Michelle Williams: int32
Michelle Yeoh: int32
Michiel Huisman: int32
Mickey Rourke: int32
Mike Birbiglia: int32
Mila Kunis: int32
Miles Teller: int32
Milla Jovovich: int32
Minako Kotobuki: int32
Mindy Kaling: int32
Minnie Driver: int32
Moises Arias: int32
Molly Parker: int32
Molly Shannon: int32
Monica Bellucci: int32
Morena Baccarin: int32
Morgan Freeman: int32
Moritz Bleibtreu: int32
Mélanie Laurent: int32
Naomi Watts: int32
Naomie Harris: int32
Natalie Portman: int32
Nate Parker: int32
Nathan Gamble: int32
Nathan Lane: int32
Navid Negahban: int32
Neal Huff: int32
Neil Patrick Harris: int32
Nicholas Hoult: int32
Nick Frost: int32
Nick Offerman: int32
Nicolas Cage: int32
Nicole Kidman: int32
Nikolaj Coster-Waldau: int32
Nils Verkooijen: int32
Nina Arianda: int32
Nina Hoss: int32
Noah Jupe: int32
Noah Segan: int32
Noah Taylor: int32
Noomi Rapace: int32
Octavia Spencer: int32
Odeya Rush: int32
Olga Kurylenko: int32
Oliver Platt: int32
Olivia Colman: int32
Olivia Cooke: int32
Olivia Thirlby: int32
Olivia Wilde: int32
Olivia Williams: int32
Omar Sy: int32
Orlando Bloom: int32
Oscar Isaac: int32
Owen Wilson: int32
Pablo Schreiber: int32
Paddy Considine: int32
Patricia Arquette: int32
Patricia Clarkson: int32
Patrick Stewart: int32
Patrick Wilson: int32
Patton Oswalt: int32
Paul Bettany: int32
Paul Dano: int32
Paul Giamatti: int32
Paul Rudd: int32
Paul Schneider: int32
Paul Walker: int32
Paul Walter Hauser: int32
Penélope Cruz: int32
Pete Postlethwaite: int32
Peter Blok: int32
Peter Dinklage: int32
Peter Mullan: int32
Peter Sarsgaard: int32
Peter Stormare: int32
Peter Van den Begin: int32
Philip Seymour Hoffman: int32
Pierce Brosnan: int32
Pierre Bokma: int32
Piper Perabo: int32
Pom Klementieff: int32
RZA: int32
Rachael Taylor: int32
Rachel McAdams: int32
Rachel Weisz: int32
Radha Mitchell: int32
Ralph Fiennes: int32
Rashida Jones: int32
Ray Liotta: int32
Ray McKinnon: int32
Ray Romano: int32
Ray Winstone: int32
Raymond Thiry: int32
Rebecca De Mornay: int32
Rebecca Ferguson: int32
Rebecca Hall: int32
Reese Witherspoon: int32
Rhys Darby: int32
Rhys Ifans: int32
Ricardo Darín: int32
Richard Armitage: int32
Richard E. Grant: int32
Richard Gere: int32
Richard Griffiths: int32
Richard Jenkins: int32
Richard Schiff: int32
Richmond Arquette: int32
Ricky Gervais: int32
Riley Keough: int32
Riz Ahmed: int32
Rob Corddry: int32
Robert Carlyle: int32
Robert De Niro: int32
Robert Downey Jr.: int32
Robert John Burke: int32
Robert Patrick: int32
Robert Pattinson: int32
Robert Redford: int32
Robin Williams: int32
Robin Wright: int32
Roger Allam: int32
Romain Duris: int32
Ron Livingston: int32
Ron Perlman: int32
Rooney Mara: int32
Rory Culkin: int32
Rosamund Pike: int32
Rosario Dawson: int32
Rose Byrne: int32
Rupert Grint: int32
Russell Brand: int32
Russell Crowe: int32
Russell Tovey: int32
Rutger Hauer: int32
Ryan Gosling: int32
Ryan Reynolds: int32
Ryunosuke Kamiki: int32
Sabine Timoteo: int32
Sacha Baron Cohen: int32
Saffron Burrows: int32
Sally Hawkins: int32
Salma Hayek: int32
Sam Claflin: int32
Sam Neill: int32
Sam Riley: int32
Sam Rockwell: int32
Sam Shepard: int32
Sam Spruell: int32
Sam Worthington: int32
Samantha Mathis: int32
Samantha Morton: int32
Samuel L. Jackson: int32
Sandra Bullock: int32
Saoirse Ronan: int32
Sarah Paulson: int32
Sarah Silverman: int32
Sarah Snook: int32
Scarlett Johansson: int32
Scoot McNairy: int32
Scott Glenn: int32
Sean Bean: int32
Sebastian Stan: int32
Selena Gomez: int32
Sergi López: int32
Seth Rogen: int32
Shailene Woodley: int32
Shea Whigham: int32
Shia LaBeouf: int32
Shirley Henderson: int32
Sienna Miller: int32
Sigourney Weaver: int32
Simon Callow: int32
Simon McBurney: int32
Simon Pegg: int32
Sophie Kennedy Clark: int32
Stacy Martin: int32
Stana Katic: int32
Stanley Tucci: int32
Stellan Skarsgård: int32
Stephen Campbell Moore: int32
Stephen Dorff: int32
Stephen Graham: int32
Stephen Lang: int32
Stephen McHattie: int32
Stephen McKinley Henderson: int32
Stephen Rea: int32
Stephen Root: int32
Steve Buscemi: int32
Steve Carell: int32
Steve Coogan: int32
Steve Zahn: int32
Steven Mackintosh: int32
Stipe Erceg: int32
Sunita Mani: int32
Susan Sarandon: int32
Susi Sánchez: int32
Sylvester Stallone: int32
T.J. Miller: int32
Taika Waititi: int32
Takahiro Sakurai: int32
Tammy Blanchard: int32
Tara Strong: int32
Taron Egerton: int32
Tate Donovan: int32
Taylor Kitsch: int32
Ted Levine: int32
Terence Stamp: int32
Teresa Palmer: int32
Terrence Howard: int32
Terry Crews: int32
Terry Notary: int32
Thandiwe Newton: int32
Thomas Bo Larsen: int32
Thomas Haden Church: int32
Thomas Jane: int32
Thomas Kretschmann: int32
Tilda Swinton: int32
Tim Allen: int32
Tim Blake Nelson: int32
Tim Guinee: int32
Tim McGraw: int32
Tim Robbins: int32
Tim Roth: int32
Timothy Hutton: int32
Timothy Olyphant: int32
Timothy Spall: int32
Timothée Chalamet: int32
Tobey Maguire: int32
Toby Jones: int32
Toby Kebbell: int32
Tom Cruise: int32
Tom Hanks: int32
Tom Hardy: int32

In [47]:
# Identifier les colonnes de type bool
bool_columns = df.select_dtypes(include='bool').columns

# Convertir les colonnes bool en int
df[bool_columns] = df[bool_columns].astype(int)

In [50]:
# 1-Sauvegarder en format CSV
df.to_csv('df.csv', index=False)